/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package ui.home.user.panels;

import data.models.Book;
import data.models.BookCopy;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.function.Consumer;

/**
 * @author GIGABIT
 */
public class BookPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookPanel1
     */
    private Consumer<Book> onBookPanelClicked;
    private int bookId;

    public BookPanel() {
        initComponents();
    }

    public static BookPanel creat(Book book, Consumer<Book> onBookPanelClicked) {
        BookPanel bookPanel = new BookPanel();

        bookPanel.setBookName(book.getTitle());
        bookPanel.setAuthor(book.getAuthor());
        bookPanel.setStatus(book.getAvailabilityStatus());
        bookPanel.onBookPanelClicked = onBookPanelClicked;
        bookPanel.setImage(book.getImagePathOrDefault());
        bookPanel.bookId = book.getBookId();
        bookPanel.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 1) {
                    onBookPanelClicked.accept(book);
                }
            }
        });

        return bookPanel;
    }

    public void setOnBookPanelClicked(Consumer<Book> onBookPanelClicked) {
        this.onBookPanelClicked = onBookPanelClicked;
    }

    public void setBookName(String bookName) {
        this.bookName.setText(bookName);
    }

    public void setAuthor(String author) {
        this.author.setText(author);
    }

    public void setStatus(BookCopy.AvailabilityStatus status) {
        this.status.setText(status.toString());
    }

    public void setImage(String imagePath) {
        try {
            BufferedImage bufferedImage = ImageIO.read(new File(imagePath));
            Image icon = bufferedImage.getScaledInstance(139, 96, Image.SCALE_SMOOTH);
            this.picBox.setIcon(new ImageIcon(icon));
        } catch (Exception ignored) {
        }
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        picBox = new javax.swing.JLabel();
        bookName = new javax.swing.JLabel();
        author = new javax.swing.JLabel();
        status = new javax.swing.JLabel();

        picBox.setText(" ");

        bookName.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        bookName.setToolTipText("");

        author.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        author.setForeground(new java.awt.Color(102, 102, 102));
        author.setToolTipText("");

        status.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        status.setForeground(new java.awt.Color(102, 102, 102));
        status.setText(" ");
        status.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(picBox, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(author, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                                        .addComponent(bookName, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                                        .addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(picBox, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bookName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(author, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel author;
    private javax.swing.JLabel bookName;
    private javax.swing.JLabel picBox;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables

}
