/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.home.admin.panels.copy;

import data.models.BookCopy;

import java.util.function.Consumer;

/**
 * @author GIGABIT
 */
public class CopyPanel extends javax.swing.JPanel {

    /**
     * Creates new form CopyItem
     */
    private Consumer<Integer> onDeleteClicked;
    private int copyId;

    public CopyPanel() {
        initComponents();
    }

    public static CopyPanel create(BookCopy copy, Consumer<Integer> onDeleteClicked) {
        CopyPanel copyPanel = new CopyPanel();

        copyPanel.copyId = copy.getCopyID();
        copyPanel.setBookName(copy.getBook().getTitle());
        copyPanel.setStatusOfBook(copy.getAvailabilityStatus());
        copyPanel.onDeleteClicked = onDeleteClicked;
        if(copy.getAvailabilityStatus().equals(BookCopy.AvailabilityStatus.BORROWED))
            copyPanel.deleteButton.setEnabled(false);
        return copyPanel;
    }

    public void setBookName(String bookName) {
        this.bookName.setText(bookName);
    }

    public void setStatusOfBook(BookCopy.AvailabilityStatus statusOfBook) {
        this.statusOfBook.setText(statusOfBook.name());
    }

    public void onDeleteClicked(Consumer<Integer> onDeleteClicked) {
        this.onDeleteClicked = onDeleteClicked;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookName = new javax.swing.JLabel();
        statusOfBook = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        bookName.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        statusOfBook.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        deleteButton.setBackground(new java.awt.Color(115, 22, 69));
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(bookName, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statusOfBook, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteButton)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(statusOfBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(bookName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(deleteButton)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        onDeleteClicked.accept(copyId);
    }//GEN-LAST:event_deleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bookName;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel statusOfBook;
    // End of variables declaration//GEN-END:variables
}
